# Generated by Django 5.2 on 2025-05-07 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biological_age', models.IntegerField()),
                ('mental_age', models.IntegerField()),
                ('identified_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.age')),
            ],
        ),
        migrations.CreateModel(
            name='Man',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firstapp.person')),
                ('beard_length', models.IntegerField()),
                ('height', models.FloatField()),
                ('amount_of_hair', models.IntegerField()),
            ],
            bases=('firstapp.person',),
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firstapp.person')),
                ('protruding_ears', models.BooleanField()),
                ('good_personality', models.BooleanField()),
                ('candy_crush_level', models.IntegerField()),
            ],
            bases=('firstapp.person',),
        ),
    ]
